function fig = plotJaccard(ordered_feature, modelNames, title, options)
arguments
    ordered_feature 
    modelNames 
    title 
    options.visible_plot ="on"
end
    Jacc_distance = 1 - squareform(pdist(ordered_feature','jaccard'));
    fig = plot_clustergram(Jacc_distance,...
                                                                     modelNames,...
                                                                     modelNames,...
                                                                     title,...
                                                                     "Jaccard similarity",...
                                                                     [255 255 255;255 204 204;...
                                                                      255 153 153; 255 102 102; ...
                                                                      255 51 51;255 0 0; 204 0 0; ...
                                                                      152 0 0; 102 0 0;  51 0 0]/255);

    set(fig,'Visible',options.visible_plot)

end